<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/* @var $block \Magento\PointRewardPromotion\Block\AccountPointReward */
?>
<?php if ($block->customerLoggedIn()): ?>
<li class="link point-reward" data-bind="scope: 'customer'">
    <a <?php /* @escapeNotVerified */ echo $block->getLinkAttributes() ?>><?php echo $block->escapeHtml($block->getLabel()) ?>
        <span data-bind="text: customer().point_reward_customer" class="counter qty"></span>
    </a>
</li>
<?php endif; ?>